version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: parserdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    depends_on:
      - db

volumes:
  pgdata:
